apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicontador
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contador
  template:
    metadata:
      labels:
        app: contador
    spec:
      containers:
        - name: apicontador
          image: tadrianonet/tadrianoaks
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
